version: "3.8"
services:
  api-gateway:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
     - "3090:3090"
    depends_on:
     - db
     - mongo
    networks:
     - crtr_net
    env_file:
    - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-bsc
    ports:
      - "5432:5432"
    networks:
      - crtr_net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - crtr_net

networks:
    crtr_net:
      name: apps-net
      external: true
      driver: bridge
   