version: "3.8"
services:
  api-gateway:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
     - "3090:3090"
    networks:
     - crtr_net
    env_file:
    - .env

networks:
    crtr_net:
      name: apps-net
      external: true 
   