import { Constantes } from '@bsc/core';

/**
 * Clase con las constantes que se usan para conectarse y acceder servicios publicados en cada micro servicio
 *
 * @export
 * @class ConstantesGw
 * @typedef {ConstantesGw}
 * @extends {Constantes}
 */
export class ConstantesGw extends Constantes {

  public static GATEWAY = {
    NAME: 'api-gateway',
  };

  public static ADMINISTRACION = {
    HOST: process.env.MS_ADMINISTRACION_HOST,
    PORT: parseInt(process.env.MS_ADMINISTRACION_PORT),
    NAME: 'ms-administracion',
    PATTERN: {
      USUARIO_COLLECTION: 'USUARIO_COLLECTION',
      USUARIO_BY_ID: 'USUARIO_BY_ID',
      USUARIO_CREATE: 'USUARIO_CREATE',
      USUARIO_UPDATE: 'USUARIO_UPDATE',
      USUARIO_DELETE: 'USUARIO_DELETE',

      MODULO_CREATE: 'MODULO_CREATE',
      MODULO_UPDATE: 'MODULO_UPDATE',
      MODULO_DELETE: 'MODULO_DELETE',
      MODULO_COLLECTION: 'MODULO_COLLECTION',
      MODULO_BY_ID: 'MODULO_BY_ID',

      MENU_CREATE: 'MENU_CREATE',
      MENU_UPDATE: 'MENU_UPDATE',
      MENU_DELETE: 'MENU_DELETE',
      MENU_COLLECTION: 'MENU_COLLECTION',
      MENU_BY_ID: 'MENU_BY_ID',

      ROL_CREATE: 'ROL_CREATE',
      ROL_UPDATE: 'ROL_UPDATE',
      ROL_DELETE: 'ROL_DELETE',
      ROL_COLLECTION: 'ROL_COLLECTION',
      ROL_BY_ID: 'ROL_BY_ID',

      ESTABLECIMIENTO_CREATE: 'ESTABLECIMIENTO_CREATE',
      ESTABLECIMIENTO_UPDATE: 'ESTABLECIMIENTO_UPDATE',
      ESTABLECIMIENTO_DELETE: 'ESTABLECIMIENTO_DELETE',
      ESTABLECIMIENTO_COLLECTION: 'ESTABLECIMIENTO_COLLECTION',
      ESTABLECIMIENTO_BY_ID: 'ESTABLECIMIENTO_BY_ID',

      PROVINCIA_COLLECTION: 'PROVINCIA_COLLECTION',
      PROVINCIA_BY_ID: 'PROVINCIA_BY_ID',

      CONFIGURACION_COLLECTION: 'CONFIGURACION_COLLECTION'
    },
  };

  public static AUTORIZACION = {
    HOST: process.env.MS_AUTORIZACION_HOST,
    PORT: parseInt(process.env.MS_AUTORIZACION_PORT),
    NAME: 'ms-autorizacion',
    PATTERN: {
      LOGIN:'LOGIN',
      PERFIL:'PERFIL',
      CAMBIO_PASSWORD:'CAMBIO_PASSWORD',
      MODULO_PERMISOS_ID:'MODULO_PERMISOS_ID',
      LOGOUT:'LOGOUT'
    },
  };

  public static DIGITALIZACION = {
    HOST: process.env.MS_ADMINISTRACION_HOST,
    PORT: parseInt(process.env.MS_ADMINISTRACION_PORT),
    NAME: 'ms-digitalizacion',
    PATTERN: {
      PROVINCIA_DIGITALIZACION_COLLECTION: 'PROVINCIA_DIGITALIZACION_COLLECTION',
      PROVINCIA_DIGITALIZACION_BY_ID: 'PROVINCIA_DIGITALIZACION_BY_ID',
      CANTON_DIGITALIZACION_COLLECTION: 'CANTON_DIGITALIZACION_COLLECTION',
      PARROQUIA_DIGITALIZACION_COLLECTION: 'PARROQUIA_DIGITALIZACION_COLLECTION',
      ZONA_DIGITALIZACION_COLLECTION: 'ZONA_DIGITALIZACION_COLLECTION',
      JUNTA_DIGITALIZACION_COLLECTION: 'JUNTA_DIGITALIZACION_COLLECTION',
      ACTA_BY_JUNTA_DIGITALIZACION_LIST: 'ACTA_BY_JUNTA_DIGITALIZACION_LIST',
      DIGNIDAD_DIGITALIZACION_COLLECTION: 'DIGNIDAD_DIGITALIZACION_COLLECTION',
      ACTA_BY_DIGNIDAD_DIGITALIZACION_LIST: 'ACTA_BY_DIGNIDAD_DIGITALIZACION_LIST',
      ACTA_UPDATE_DIG_DIGITALIZACIION: 'ACTA_UPDATE_DIG_DIGITALIZACIION',

      VOTOS_UPDATE_DIG_DIGITALIZACION: 'VOTOS_UPDATE_DIG_DIGITALIZACION',
      ACTA_COLLECTION_DIGITALIZACION: 'ACTA_COLLECTION_DIGITALIZACION',
      ACTA_LIBERA_DIGITALIZACION: 'ACTA_LIBERA_DIGITALIZACION'
    },
  };

  public static VERIFICACION = {
    HOST: process.env.MS_VERIFICACION_HOST,
    PORT: parseInt(process.env.MS_VERIFICACION_PORT),
    NAME: 'ms-verificacion',
    PATTERN: {
      PROVINCIA_VERIFICACION_COLLECTION: 'PROVINCIA_VERIFICACION_COLLECTION',
      PROVINCIA_VERIFICACION_BY_ID: 'PROVINCIA_VERIFICACION_BY_ID'
    },
  };


  public static REPORTES = {
    HOST: process.env.MS_REPORTES_HOST,
    PORT: parseInt(process.env.MS_REPORTES_PORT),
    NAME: 'ms-reportes',
    PATTERN: {
      PROVINCIA_REPORTES_COLLECTION: 'PROVINCIA_REPORTES_COLLECTION',
      PROVINCIA_REPORTES_BY_ID: 'PROVINCIA_REPORTES_BY_ID'
    },
  };
}
